version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - git submodule update --init --recursive
  - nuget restore script\csharp\DIVATools.sln
build_script:
#  - .\build.release.bat
  - dotnet restore script\csharp\DIVATools.sln
  - dotnet clean script\csharp\DIVATools.sln
  - dotnet build script\csharp\DIVATools.sln
test_script:
  - cd Tests
  - dotnet test