configuration: Release

version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - git submodule update --init --recursive
  - nuget restore script\csharp\DIVATools.sln
build_script:
#  - .\build.release.bat
  - dotnet restore script\csharp\DIVATools.sln
  - dotnet clean script\csharp\DIVATools.sln
  - dotnet build script\csharp\DIVATools.sln
artifacts:
  - path: bin\A3DA2XML\$(configuration)
    name: A3DA2XML
  
  - path: bin\DBTools\$(configuration)
    name: DBTools

  - path: bin\FarcPack\$(configuration)
    name: FarcPack

  - path: bin\FDSC\$(configuration)
    name: FDSC
    
  - path: bin\lib\DIVALib\$(configuration)
    name: DIVALib

  - path: bin\TXP2DDS\$(configuration)
    name: TXP2DDS
